### ISSUE TITLE
[Samuel-Pelletier-Evraire] - Issue with merging json file

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/harvester-prototype#2]
I need to read two JSON files and then merge them together to form one JSON file that I can send to the API. One of the two files contains all the keys and the other contains all the questions. When I want to merge them, they are supposed to give key: question, but it doesn't work as expected. Firstly, the key doesn't display, and secondly, a number appears between the key and the question.

Here the result i got : 

29, Is the fertiliser contain phosphore or phosphorous

The expected result would be : 
contain_phosphoric_acid : Did the fertilizer contain phosphorous?

Here how keys.json is write:
"name_of_the_registrant": null,
"address_of_the_registrant": null,

Here how questions.json is write: 
"1": "Give the name of the manufacturer or registrant of the fertiliser or supplement",
"2": "Give the full address of the manufacturer or registrant (address must include: street address or post office box number, city, province or state and postal code or ZIP code, as applicable), and the country, if the product is manufactured outside of Canada",

https://github.com/ai-cfia/harvester-prototype/blob/e273e4c792c6a29b72c687f6393ab643639f7035/app.py#L62C1-L74C25

**Comment by MaxenceGui** [comment]
The first thing I notice is that you don't seem to use the data from the keys_data that you are loading. So when you iterate through questions_data.items() you only use the value from the question_file.

https://github.com/ai-cfia/harvester-prototype/blob/e273e4c792c6a29b72c687f6393ab643639f7035/app.py#L65

It's harder to notice on GitHub, but you can see it on vscode.

![image](https://github.com/ai-cfia/harvester-prototype/assets/96267006/1e3a5dd2-57cd-49fb-a32a-a6a76d0737c0)

Also if your JSON question looks like this:

```json
{
  "question":{
       "1": "first question",
       "2": "second question"
   }
}
```

Then you can expect your key to be a number, and your value having a question.

I would suggest the use of enumerate in this case. However, this expects the keys.json and the questions.json to be the same length.


```python
# Assuming that you get a list from your JSON (keys and questions)
for index, value in enumerate(questions_data):
    key = keys_data[index] # supposing that keys_data is a list
    temp_data[key] = questions_data[value] # value here will be the keys from questions_data if dict
```

I don't exactly know how your JSONs are formatted, but I would expect it to look like this or the above:

```json
{
  "question":[
       "first question",
       "second question"
   ]
}

{
  "keys":[
       "first key",
       "second key"
   ]
}
```

Feel free to adapt this proposition to how your JSONs are built or correct me if I misunderstand your issue. 😄

**Comment by rngadam** [comment]
@SamuelPelletierEvraire as discussed verbally, merging JSON wasn't something needed as we want the source of truth to be from the spreadsheet.
